### ISSUE TITLE
Problem building windows-cmake branch

### ISSUE THREAD

**Issue by djetter99** [willyd/caffe#23]
When I try to execute `cmake --build . --config %CMAKE_CONFIGURATION%`, I get an error:
`ninja: error: loading 'build.ninja': The system cannot find the file specified.`

I am using Windows 10, Visual Studio 2015, CMake 3.7.0-rc1, Python 2.7, and Ninja 1.6.0.

I used caffe-builder to build the dependencies myself using Ninja. (I did have to fix one bug in build_v140_x64.cmd: The second line in the file should be 'if not **EXIST** build_v140_x64', rather than 'if not **EXISTS** build_v140_x64'.)

I then attempted to execute the commands described in the readme.md:

```
call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
set CMAKE_GENERATOR=Ninja
set CMAKE_CONFIGURATION=Release
set CAFFE_DEPENDENCIES=<my path>\caffe-builder\build_v140_x64\libraries
mkdir build
cd build
cmake -G%CMAKE_GENERATOR% -DBLAS=Open -DCMAKE_BUILD_TYPE=%CMAKE_CONFIGURATION% -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=<my path>\caffe\install -C %CAFFE_DEPENDENCIES%\caffe-builder-config.cmake  ..\
cmake --build . --config %CMAKE_CONFIGURATION%
```

If you need any other information, please let me know.

**Comment by willyd** [comment]
@djetter99 What's inside the build folder? Isn't there a build.ninja file? Are you executing the command from the build folder?

**Comment by willyd** [comment]
> The second line in the file should be 'if not EXIST build_v140_x64', rather than 'if not EXISTS build_v140_x64'.)

Fixed.

**Comment by djetter99** [comment]
@willyd Here are the contents of the build folder:

```
10/08/2016  12:14 PM    <DIR>          caffe
10/08/2016  12:14 PM             2,629 CaffeConfig.cmake
10/08/2016  12:14 PM             3,907 CaffeTargets.cmake
10/08/2016  12:14 PM               629 caffe_config.h
10/08/2016  12:14 PM    <DIR>          cmake
10/08/2016  12:14 PM            48,905 CMakeCache.txt
10/08/2016  12:14 PM    <DIR>          CMakeFiles
10/08/2016  12:14 PM             3,367 cmake_install.cmake
10/08/2016  12:14 PM               363 detect_cuda_archs.cu
10/08/2016  12:14 PM    <DIR>          docs
10/08/2016  12:14 PM    <DIR>          examples
10/08/2016  12:14 PM    <DIR>          lib
10/08/2016  12:14 PM    <DIR>          matlab
10/08/2016  12:14 PM    <DIR>          python
10/08/2016  12:14 PM    <DIR>          src
10/08/2016  12:14 PM    <DIR>          test
10/08/2016  12:14 PM    <DIR>          tools
10/08/2016  12:14 PM                 0 __init__.py
```

I am running the commands from the build folder. I saw a few errors when I ran caffe-builder-config.cmake, but I didn't think they were serious. Here are the snippets:

-- Could NOT find NumPy (missing:  NUMPY_INCLUDE_DIR NUMPY_VERSION) (Required is at least version "1.7.1")
-- Python interface is disabled or not all required dependencies found. Building without it...

CMake Error at CMakeLists.txt:111 (add_dependencies):
  The dependency target "pycaffe" of target "pytest" does not exist.

CMake Warning (dev):
  Policy CMP0058 is not set: Ninja requires custom command byproducts to be
  explicit. 

I can dump the entire output of the command if you like.

**Comment by djetter99** [comment]
Here is a quick update on my progress: I believe that the reason that the build.ninja file is missing is because I did not have numpy installed. I fixed that problem by installing Anaconda 4.2.0, Python 2.7 64-bit. The next problem that I ran into is that Visual Studio 2015 is not supported by CUDA 7.5, so now I am installing CUDA 8.0.

**Comment by djetter99** [comment]
I installed CUDA 8.0, but now when I execute the command, I keep seeing this error:
`LINK : fatal error LNK1181: cannot open input file 'zlib-shared.lib'`

I used build_v140_x64.cmd, which specifies the following flag: `-D ZLIB_BUILD_SHARED_LIBS:BOOL=ON`

However, in caffe-builder\build_v140_x64\libraries\lib, I only see these files:

```
zlib.lib
zlibd.lib
zlibstatic.lib
zlibstaticd.lib
```

So, for some reason, it seems like zlib-shared.lib is not being built?

**Comment by djetter99** [comment]
I think the zlib.lib error occurred because I built the dependencies without numpy, and I was trying to build caffe with numpy. Once I went back and rebuilt the dependencies with Anaconda installed, I got past that point. Now it seems like I was able to build caffe.exe! 

However, my build proces still failed, because when it tried to link lib/_caffe.pyd, there were some unresolved external symbols (I shortened each name):

```
_caffe.cpp.obj : error LNK2019: unresolved external symbol "class caffe::Solver<float> ... 
_caffe.cpp.obj : error LNK2019: unresolved external symbol "class caffe::Net<float>  ...
_caffe.cpp.obj : error LNK2019: unresolved external symbol "class caffe::NesterovSolver<float>  ...
_caffe.cpp.obj : error LNK2019: unresolved external symbol "class caffe::AdaGradSolver<float>  ...
_caffe.cpp.obj : error LNK2019: unresolved external symbol "class caffe::RMSPropSolver<float>  ...
_caffe.cpp.obj : error LNK2019: unresolved external symbol "class caffe::AdaDeltaSolver<float>  ...
_caffe.cpp.obj : error LNK2019: unresolved external symbol "class caffe::AdamSolver<float> ...
```

**Comment by djetter99** [comment]
I'm not sure what is causing the unresolved external symbols. In `build.ninja,` I see that `adadelta_solver.cpp.obj` is compiled into `lib\caffe.lib`, and I see that `lib\caffe.lib` is linked into `lib\_caffe.pyd`. But I still get an unresolved external symbol for `AdaDeltaSolver<float>`.

So, I bypassed the problem by setting `-DBUILD_python=OFF -DBUILD_python_layer=OFF` in my cmake command.

After that, I was able to successfully complete the build. 

However, I do intermittently see errors while building the .exe files, and then those errors go away if I run the build command again. The errors are always of this form, but the particular exe that fails is always different:

```
[1/9] Linking CXX executable examples\cifar10\convert_cifar_data.exe
FAILED: examples/cifar10/convert_cifar_data.exe 
...
C:/Program Files (x86)/Windows Kits/8.1/bin/x64/mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "examples\cifar10\convert_cifar_data.exe". The system cannot open the device or file specified.
```

I'm guessing there is some sort of race condition going on here, but I don't know what it is.

**Comment by djetter99** [comment]
Okay, I just disabled my virus scanner, and that fixed the intermittent errors! Woo!

However, I still see the unresolved external symbols if I attempt to build `_caffe.pyd`. So, I'm still bypassing the python build with `-DBUILD_python=OFF -DBUILD_python_layer=OFF`.

**Comment by willyd** [comment]
Closing the official windows branch on the BVLC repo has full python 2.7 support.
